import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { z } from "zod";
import { generatePpt } from "@/lib/ppt";
import { ReportPayload } from "@/lib/types";

const emailReportSchema = z.object({
  email: z.string().email().max(254),
  report: z.custom<ReportPayload>()
});

function slugify(name: string): string {
  return name.replace(/[^a-z0-9]/gi, "-").replace(/-+/g, "-").replace(/^-|-$/g, "").toLowerCase() || "report";
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  try {
    const apiKey = process.env.RESEND_API_KEY;
    const fromEmail = process.env.RESEND_FROM_EMAIL;

    if (!apiKey || !fromEmail) {
      return NextResponse.json(
        {
          message: "Email is not configured. Set RESEND_API_KEY and RESEND_FROM_EMAIL in .env.local."
        },
        { status: 503 }
      );
    }

    const { email, report } = emailReportSchema.parse(await request.json());
    const buffer = await generatePpt(report);
    const filename = `${slugify(report.primaryCompany)}-video-benchmark.pptx`;

    const resend = new Resend(apiKey);
    const { error } = await resend.emails.send({
      from: fromEmail,
      to: [email],
      subject: `Video Benchmark Report – ${report.primaryCompany}`,
      html: `
        <div style="font-family: system-ui, sans-serif; max-width: 560px; color: #0f172a;">
          <h2 style="color: #0d9488; margin-bottom: 8px;">Video Marketing Intelligence Report</h2>
          <p style="color: #64748b; line-height: 1.6;">
            Your benchmark deck for <strong>${report.primaryCompany}</strong> is attached.
            It includes competitive scores, engagement analysis, gap opportunities, and posting-time insights.
          </p>
          <p style="font-size: 13px; color: #94a3b8;">Generated by Mypromovdos · ${new Date(report.requestedAt).toLocaleDateString()}</p>
        </div>
      `,
      attachments: [
        {
          filename,
          content: buffer
        }
      ]
    });

    if (error) {
      return NextResponse.json(
        { message: "Failed to send email.", details: error.message },
        { status: 502 }
      );
    }

    return NextResponse.json({ ok: true });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ message: "Invalid email or report payload." }, { status: 400 });
    }

    return NextResponse.json(
      {
        message: "Failed to email report.",
        details: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 500 }
    );
  }
}
